pkname="models"
output="db/models"
[psql]
  dbname = "dynamic_novel"
  host   = "db"
  port   = 5432
  user   = "postgres"
  pass   = "pass"
  sslmode = "disable"
  schema = "public"
  blacklist = ["migrations", "other"]

[[types]]
  [types.match]
    type = "null.Int"
    nullable = true

  [types.replace]
    type = "null.Int32"

  [types.imports]
    third_party = ['"github.com/volatiletech/null/v8"']

[[types]]
  [types.match]
    type = "int"

  [types.replace]
    type = "int32"
