// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSections(t *testing.T) {
	t.Parallel()

	query := Sections()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSectionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSectionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Sections().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSectionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SectionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSectionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SectionExists(ctx, tx, o.SectionID)
	if err != nil {
		t.Errorf("Unable to check if Section exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SectionExists to return true, but got false.")
	}
}

func testSectionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	sectionFound, err := FindSection(ctx, tx, o.SectionID)
	if err != nil {
		t.Error(err)
	}

	if sectionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSectionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Sections().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSectionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Sections().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSectionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	sectionOne := &Section{}
	sectionTwo := &Section{}
	if err = randomize.Struct(seed, sectionOne, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}
	if err = randomize.Struct(seed, sectionTwo, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sectionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sectionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Sections().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSectionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	sectionOne := &Section{}
	sectionTwo := &Section{}
	if err = randomize.Struct(seed, sectionOne, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}
	if err = randomize.Struct(seed, sectionTwo, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sectionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sectionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func sectionBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func sectionAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func sectionAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func sectionBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func sectionAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func sectionBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func sectionAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func sectionBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func sectionAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Section) error {
	*o = Section{}
	return nil
}

func testSectionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Section{}
	o := &Section{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, sectionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Section object: %s", err)
	}

	AddSectionHook(boil.BeforeInsertHook, sectionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	sectionBeforeInsertHooks = []SectionHook{}

	AddSectionHook(boil.AfterInsertHook, sectionAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	sectionAfterInsertHooks = []SectionHook{}

	AddSectionHook(boil.AfterSelectHook, sectionAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	sectionAfterSelectHooks = []SectionHook{}

	AddSectionHook(boil.BeforeUpdateHook, sectionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	sectionBeforeUpdateHooks = []SectionHook{}

	AddSectionHook(boil.AfterUpdateHook, sectionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	sectionAfterUpdateHooks = []SectionHook{}

	AddSectionHook(boil.BeforeDeleteHook, sectionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	sectionBeforeDeleteHooks = []SectionHook{}

	AddSectionHook(boil.AfterDeleteHook, sectionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	sectionAfterDeleteHooks = []SectionHook{}

	AddSectionHook(boil.BeforeUpsertHook, sectionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	sectionBeforeUpsertHooks = []SectionHook{}

	AddSectionHook(boil.AfterUpsertHook, sectionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	sectionAfterUpsertHooks = []SectionHook{}
}

func testSectionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSectionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(sectionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSectionToManyTerms(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c Term

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, termDBTypes, false, termColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, termDBTypes, false, termColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.SectionID, a.SectionID)
	queries.Assign(&c.SectionID, a.SectionID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Terms().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.SectionID, b.SectionID) {
			bFound = true
		}
		if queries.Equal(v.SectionID, c.SectionID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SectionSlice{&a}
	if err = a.L.LoadTerms(ctx, tx, false, (*[]*Section)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Terms); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Terms = nil
	if err = a.L.LoadTerms(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Terms); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSectionToManyAddOpTerms(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c, d, e Term

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Term{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, termDBTypes, false, strmangle.SetComplement(termPrimaryKeyColumns, termColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Term{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddTerms(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.SectionID, first.SectionID) {
			t.Error("foreign key was wrong value", a.SectionID, first.SectionID)
		}
		if !queries.Equal(a.SectionID, second.SectionID) {
			t.Error("foreign key was wrong value", a.SectionID, second.SectionID)
		}

		if first.R.Section != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Section != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Terms[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Terms[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Terms().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSectionToManySetOpTerms(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c, d, e Term

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Term{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, termDBTypes, false, strmangle.SetComplement(termPrimaryKeyColumns, termColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetTerms(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Terms().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetTerms(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Terms().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SectionID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SectionID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.SectionID, d.SectionID) {
		t.Error("foreign key was wrong value", a.SectionID, d.SectionID)
	}
	if !queries.Equal(a.SectionID, e.SectionID) {
		t.Error("foreign key was wrong value", a.SectionID, e.SectionID)
	}

	if b.R.Section != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Section != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Section != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Section != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Terms[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Terms[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testSectionToManyRemoveOpTerms(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c, d, e Term

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Term{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, termDBTypes, false, strmangle.SetComplement(termPrimaryKeyColumns, termColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddTerms(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Terms().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveTerms(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Terms().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SectionID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SectionID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Section != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Section != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Section != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Section != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Terms) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Terms[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Terms[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testSectionToOneFontUsingFont(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Section
	var foreign Font

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, fontDBTypes, false, fontColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Font struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.FontID = foreign.FontID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Font().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.FontID != foreign.FontID {
		t.Errorf("want: %v, got %v", foreign.FontID, check.FontID)
	}

	ranAfterSelectHook := false
	AddFontHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Font) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SectionSlice{&local}
	if err = local.L.LoadFont(ctx, tx, false, (*[]*Section)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Font == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Font = nil
	if err = local.L.LoadFont(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Font == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSectionToOneColorUsingFrameColor(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Section
	var foreign Color

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, colorDBTypes, false, colorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Color struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.FrameColorID = foreign.ColorID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.FrameColor().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ColorID != foreign.ColorID {
		t.Errorf("want: %v, got %v", foreign.ColorID, check.ColorID)
	}

	ranAfterSelectHook := false
	AddColorHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Color) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SectionSlice{&local}
	if err = local.L.LoadFrameColor(ctx, tx, false, (*[]*Section)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.FrameColor == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.FrameColor = nil
	if err = local.L.LoadFrameColor(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.FrameColor == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSectionToOneImageUsingImage(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Section
	var foreign Image

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, imageDBTypes, false, imageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Image struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.ImageID, foreign.ImageID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Image().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ImageID, foreign.ImageID) {
		t.Errorf("want: %v, got %v", foreign.ImageID, check.ImageID)
	}

	ranAfterSelectHook := false
	AddImageHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Image) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SectionSlice{&local}
	if err = local.L.LoadImage(ctx, tx, false, (*[]*Section)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Image == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Image = nil
	if err = local.L.LoadImage(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Image == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSectionToOnePageUsingPage(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Section
	var foreign Page

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, pageDBTypes, false, pageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Page struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.PageID = foreign.PageID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Page().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.PageID != foreign.PageID {
		t.Errorf("want: %v, got %v", foreign.PageID, check.PageID)
	}

	ranAfterSelectHook := false
	AddPageHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Page) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SectionSlice{&local}
	if err = local.L.LoadPage(ctx, tx, false, (*[]*Section)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Page == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Page = nil
	if err = local.L.LoadPage(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Page == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSectionToOneColorUsingTextColor(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Section
	var foreign Color

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, colorDBTypes, false, colorColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Color struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TextColorID = foreign.ColorID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.TextColor().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ColorID != foreign.ColorID {
		t.Errorf("want: %v, got %v", foreign.ColorID, check.ColorID)
	}

	ranAfterSelectHook := false
	AddColorHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Color) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SectionSlice{&local}
	if err = local.L.LoadTextColor(ctx, tx, false, (*[]*Section)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TextColor == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.TextColor = nil
	if err = local.L.LoadTextColor(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TextColor == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSectionToOneTypeUsingType(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Section
	var foreign Type

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sectionDBTypes, false, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, typeDBTypes, false, typeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Type struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TypeID = foreign.TypeID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Type().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.TypeID != foreign.TypeID {
		t.Errorf("want: %v, got %v", foreign.TypeID, check.TypeID)
	}

	ranAfterSelectHook := false
	AddTypeHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Type) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SectionSlice{&local}
	if err = local.L.LoadType(ctx, tx, false, (*[]*Section)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Type == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Type = nil
	if err = local.L.LoadType(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Type == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSectionToOneSetOpFontUsingFont(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c Font

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, fontDBTypes, false, strmangle.SetComplement(fontPrimaryKeyColumns, fontColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, fontDBTypes, false, strmangle.SetComplement(fontPrimaryKeyColumns, fontColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Font{&b, &c} {
		err = a.SetFont(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Font != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Sections[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.FontID != x.FontID {
			t.Error("foreign key was wrong value", a.FontID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.FontID))
		reflect.Indirect(reflect.ValueOf(&a.FontID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.FontID != x.FontID {
			t.Error("foreign key was wrong value", a.FontID, x.FontID)
		}
	}
}
func testSectionToOneSetOpColorUsingFrameColor(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c Color

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, colorDBTypes, false, strmangle.SetComplement(colorPrimaryKeyColumns, colorColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, colorDBTypes, false, strmangle.SetComplement(colorPrimaryKeyColumns, colorColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Color{&b, &c} {
		err = a.SetFrameColor(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.FrameColor != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.FrameColorSections[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.FrameColorID != x.ColorID {
			t.Error("foreign key was wrong value", a.FrameColorID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.FrameColorID))
		reflect.Indirect(reflect.ValueOf(&a.FrameColorID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.FrameColorID != x.ColorID {
			t.Error("foreign key was wrong value", a.FrameColorID, x.ColorID)
		}
	}
}
func testSectionToOneSetOpImageUsingImage(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c Image

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, imageDBTypes, false, strmangle.SetComplement(imagePrimaryKeyColumns, imageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, imageDBTypes, false, strmangle.SetComplement(imagePrimaryKeyColumns, imageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Image{&b, &c} {
		err = a.SetImage(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Image != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Sections[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.ImageID, x.ImageID) {
			t.Error("foreign key was wrong value", a.ImageID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ImageID))
		reflect.Indirect(reflect.ValueOf(&a.ImageID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.ImageID, x.ImageID) {
			t.Error("foreign key was wrong value", a.ImageID, x.ImageID)
		}
	}
}

func testSectionToOneRemoveOpImageUsingImage(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b Image

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, imageDBTypes, false, strmangle.SetComplement(imagePrimaryKeyColumns, imageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetImage(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveImage(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Image().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Image != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.ImageID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Sections) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testSectionToOneSetOpPageUsingPage(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c Page

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pageDBTypes, false, strmangle.SetComplement(pagePrimaryKeyColumns, pageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, pageDBTypes, false, strmangle.SetComplement(pagePrimaryKeyColumns, pageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Page{&b, &c} {
		err = a.SetPage(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Page != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Sections[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PageID != x.PageID {
			t.Error("foreign key was wrong value", a.PageID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PageID))
		reflect.Indirect(reflect.ValueOf(&a.PageID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PageID != x.PageID {
			t.Error("foreign key was wrong value", a.PageID, x.PageID)
		}
	}
}
func testSectionToOneSetOpColorUsingTextColor(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c Color

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, colorDBTypes, false, strmangle.SetComplement(colorPrimaryKeyColumns, colorColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, colorDBTypes, false, strmangle.SetComplement(colorPrimaryKeyColumns, colorColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Color{&b, &c} {
		err = a.SetTextColor(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.TextColor != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TextColorSections[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TextColorID != x.ColorID {
			t.Error("foreign key was wrong value", a.TextColorID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TextColorID))
		reflect.Indirect(reflect.ValueOf(&a.TextColorID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TextColorID != x.ColorID {
			t.Error("foreign key was wrong value", a.TextColorID, x.ColorID)
		}
	}
}
func testSectionToOneSetOpTypeUsingType(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Section
	var b, c Type

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sectionDBTypes, false, strmangle.SetComplement(sectionPrimaryKeyColumns, sectionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, typeDBTypes, false, strmangle.SetComplement(typePrimaryKeyColumns, typeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, typeDBTypes, false, strmangle.SetComplement(typePrimaryKeyColumns, typeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Type{&b, &c} {
		err = a.SetType(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Type != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Sections[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TypeID != x.TypeID {
			t.Error("foreign key was wrong value", a.TypeID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TypeID))
		reflect.Indirect(reflect.ValueOf(&a.TypeID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TypeID != x.TypeID {
			t.Error("foreign key was wrong value", a.TypeID, x.TypeID)
		}
	}
}

func testSectionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSectionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SectionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSectionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Sections().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	sectionDBTypes = map[string]string{`SectionID`: `integer`, `Order`: `integer`, `Text`: `text`, `TextSize`: `integer`, `PageID`: `integer`, `TypeID`: `integer`, `ImageID`: `integer`, `FontID`: `integer`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`, `FrameColorID`: `integer`, `Name`: `character varying`, `TextColorID`: `integer`, `TermID`: `integer`}
	_              = bytes.MinRead
)

func testSectionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(sectionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(sectionAllColumns) == len(sectionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSectionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(sectionAllColumns) == len(sectionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Section{}
	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sectionDBTypes, true, sectionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(sectionAllColumns, sectionPrimaryKeyColumns) {
		fields = sectionAllColumns
	} else {
		fields = strmangle.SetComplement(
			sectionAllColumns,
			sectionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SectionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSectionsUpsert(t *testing.T) {
	t.Parallel()

	if len(sectionAllColumns) == len(sectionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Section{}
	if err = randomize.Struct(seed, &o, sectionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Section: %s", err)
	}

	count, err := Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, sectionDBTypes, false, sectionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Section struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Section: %s", err)
	}

	count, err = Sections().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
